name: Update Solved Badge

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  update-badge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        persist-credentials: true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Update solved badge in README
      run: |
        python .github/scripts/update_solved_badge.py

    - name: Commit and push if README.md changed
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

        if git diff --quiet; then
          echo "✅ No changes to commit."
        else
          git add README.md
          git commit -m "docs(readme): auto-update solved problems count badge"
          git push
        fi
