name: Update Solved Badge

on:
  push:
    branches: [ main ]

jobs:
  update-badge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Update solved badge in README
      run: |
        python .github/scripts/update_solved_badge.py
